#!/usr/bin/env bash
set -u

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd -P)"
OUT="$ROOT/docs/codex/agent-control/evidence/latest-status.md"

{
  echo "# Latest Status Evidence"
  echo
  echo "Observed from:"
  echo
  echo '```text'
  echo "$ROOT"
  echo '```'
  echo
  echo "Local machine time:"
  echo
  echo '```text'
  date +"%Y-%m-%d %H:%M:%S %z"
  echo '```'
  echo
  echo "## Repository"
  echo
  echo '```text'
  echo "> git status --short --branch"
  git -C "$ROOT" status --short --branch 2>&1
  echo '```'
  echo
  echo '```text'
  echo "> git rev-parse --show-toplevel"
  git -C "$ROOT" rev-parse --show-toplevel 2>&1
  echo '```'
  echo
  echo '```text'
  echo "> git log --oneline -5"
  git -C "$ROOT" log --oneline -5 2>&1
  echo '```'
  echo
  echo '```text'
  echo "> git remote -v"
  git -C "$ROOT" remote -v 2>&1
  echo '```'
  echo
  echo '```text'
  echo "> git worktree list"
  git -C "$ROOT" worktree list 2>&1
  echo '```'
  echo
  if command -v gh >/dev/null 2>&1; then
    echo '```json'
    echo "> gh pr list --state open --json number,title,headRefName,baseRefName,isDraft,mergeable,url,updatedAt"
    gh pr list --state open --json number,title,headRefName,baseRefName,isDraft,mergeable,url,updatedAt 2>&1
    echo '```'
  else
    echo "GitHub CLI not found; open PR list was not refreshed."
  fi
  echo
  echo "## Notes"
  echo
  echo "- Generated by \`docs/codex/update-status.sh\`."
  echo "- Refresh before edits, cleanup, commits, PRs, live checks, or trading readiness claims."
} > "$OUT"

echo "Updated $OUT"
