param(
  [switch]$SkipFetch
)

$ErrorActionPreference = "Stop"

$WorkspaceRoot = Split-Path -Parent $PSScriptRoot
$EvidencePath = Join-Path $PSScriptRoot "evidence\latest-status.md"

$Repos = @(
  [pscustomobject]@{
    Name = "PovertyKillerEA"
    Path = "C:\Users\NewAdmin\Documents\GitHub\PovertyKillerEA"
    Repo = "wrayboss/PovertyKillerEA"
  },
  [pscustomobject]@{
    Name = "claude-tradingview-mcp-trading"
    Path = "C:\Users\NewAdmin\claude-tradingview-mcp-trading"
    Repo = "wrayboss/claude-tradingview-mcp-trading"
  }
)

function Add-Block {
  param(
    [System.Collections.Generic.List[string]]$Lines,
    [string]$Language,
    [string[]]$Content
  )

  $Lines.Add('```' + $Language)
  if ($Content -and $Content.Count -gt 0) {
    foreach ($line in $Content) { $Lines.Add($line) }
  } else {
    $Lines.Add("(no output)")
  }
  $Lines.Add('```')
}

function Invoke-Capture {
  param(
    [string]$WorkingDirectory,
    [string[]]$Command
  )

  $previousErrorActionPreference = $ErrorActionPreference
  $ErrorActionPreference = "Continue"
  try {
    $output = & $Command[0] @($Command | Select-Object -Skip 1) 2>&1
  } finally {
    $ErrorActionPreference = $previousErrorActionPreference
  }
  $code = $LASTEXITCODE
  $lines = @()
  $lines += "> $($Command -join ' ')"
  $lines += "exit_code: $code"
  if ($output) {
    $lines += $output | ForEach-Object { "$_" }
  }
  return $lines
}

$lines = [System.Collections.Generic.List[string]]::new()
$timestamp = Get-Date -Format "yyyy-MM-dd HH:mm:ss zzz"

$lines.Add("# Latest Status Evidence")
$lines.Add("")
$lines.Add("Observed from:")
$lines.Add("")
$lines.Add("``````text")
$lines.Add($WorkspaceRoot)
$lines.Add("``````")
$lines.Add("")
$lines.Add("Local machine time:")
$lines.Add("")
$lines.Add("``````text")
$lines.Add($timestamp)
$lines.Add("``````")
$lines.Add("")
$lines.Add("## Repositories")
$lines.Add("")

foreach ($repo in $Repos) {
  $lines.Add("### $($repo.Name)")
  $lines.Add("")
  $lines.Add("Path:")
  $lines.Add("")
  $lines.Add("``````text")
  $lines.Add($repo.Path)
  $lines.Add("``````")
  $lines.Add("")

  if (-not (Test-Path -LiteralPath $repo.Path)) {
    $lines.Add("Path does not exist.")
    $lines.Add("")
    continue
  }

  Push-Location -LiteralPath $repo.Path
  try {
    if (-not $SkipFetch) {
      Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "fetch", "--all", "--prune"))
      $lines.Add("")
    }

    Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "status", "--short", "--branch"))
    $lines.Add("")
    Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "rev-parse", "--show-toplevel"))
    $lines.Add("")
    Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "log", "--oneline", "-5"))
    $lines.Add("")
    Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "remote", "-v"))
    $lines.Add("")
    Add-Block $lines "text" (Invoke-Capture $repo.Path @("git", "worktree", "list"))
    $lines.Add("")

    $gh = Get-Command gh -ErrorAction SilentlyContinue
    if ($gh) {
      Add-Block $lines "json" (Invoke-Capture $repo.Path @("gh", "pr", "list", "--repo", $repo.Repo, "--state", "open", "--json", "number,title,headRefName,baseRefName,isDraft,mergeable,url,updatedAt"))
      $lines.Add("")
    } else {
      $lines.Add("GitHub CLI not found; open PR list was not refreshed.")
      $lines.Add("")
    }
  } finally {
    Pop-Location
  }
}

$lines.Add("## Notes")
$lines.Add("")
$lines.Add('- This file is generated by `agent-control\update-status.ps1`.')
$lines.Add("- Refresh before edits, cleanup, commits, PRs, live checks, or trading readiness claims.")
$lines.Add("- The script fetches remote refs unless `-SkipFetch` is passed.")

Set-Content -LiteralPath $EvidencePath -Value $lines -Encoding UTF8
Write-Output "Updated $EvidencePath"
